name: Test con Gradle

on:
  push:
    branches:
      - main 

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout del código fuente
      uses: actions/checkout@v3
      
    - name: Configurar JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17' 
        distribution: 'adopt'
    - name: setup gradle
      uses: gradle/actions/setup-gradle@v3
      
    - name: Ejecutar pruebas con Gradle
      run: gradle test --tests "com.example.calculadora.matTest"

    - name: guardar resultados
      run: gradle :app:testDebugUnitTest --tests "com.example.calculadora.matTest" > results.txt

    - name: xd
      run: dir

    
