name: Test con Gradle

on:
  push:
    branches:
      - main 

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout del código fuente
      uses: actions/checkout@v3
      
    - name: Configurar JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17' 
        distribution: 'adopt'
    - name: setup gradle
      uses: gradle/actions/setup-gradle@v3
      
    - name: Ejecutar pruebas con Gradle
      run: gradle :app:testDebugUnitTest --tests "com.example.calculadora.matTest"

    - name: guardar resultados
      run: gradle :app:testDebugUnitTest --tests "com.example.calculadora.matTest" > results.txt

    - name: autocommit
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
         commit_message: resultados del test
         commit_user_name: Carlos el bot
         commit_user_email: orjuelacarlos80@gmail.com
         commit_autor: nose
         
          
