name: Test con Gradle

on:
  push:
    branches:
      - main 

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout del código fuente
      uses: actions/checkout@v3
      
    - name: Configurar JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11' 
        
    - name: Ejecutar pruebas con Gradle
      run: ./gradlew test
